### ISSUE TITLE
Why not support company use case?

### ISSUE THREAD

**Issue by ricardasomni** [mattdsteele/town-tester#4]
Our use case: we'd like to find out test metrics for the company owned repositories (~300 of them). 
If there was an option to authenticate and search by repo owner - would make so much more sense than counting tests by user town.

**Comment by mattdsteele** [comment]
Hey @ricardasomni, your use case sounds great! We do this at my company too.

I probably wouldn't use this repo as a starting point, though. If you've got a CI process that runs your tests, it probably would be more efficient to grab metrics from there, rather than a batch process like we've got going here. There's definitely lots of systems (as well as commercial products) that have been built with this approach.

Sorry for the late reply, hope you got a process in place!
